### ISSUE TITLE
RFE: cli plugins help text

### ISSUE THREAD

**Issue by jburel** [ome/omero-cli-duplicate#5]
In the output of ``bin/omero duplicate -h``
The following ``...if the duplicate had been run.`` possibly means to say something like ``just like if the duplicate was run``.
Possibly the complex tense is expressing it, but I would vote for a more down-to-earth formulation. I cannot help thinking that it means ``if the duplicate was run`` which makes no sense, because this is a ``--dry-run``

```
    # Do a dry run of a duplicate reporting the outcome
    # if the duplicate had been run
    omero duplicate Dataset:53 --dry-run
```

**Comment by joshmoore** [comment]
from rsync:

```
        -n, --dry-run               show what would have been transferred
```

from patch:

```
          Print the results of applying the patches without actually changing any files.
```

from make:

```
            Print the commands that would be executed, but do not execute them.
```

**Comment by pwalczysko** [comment]
> from rsync:
> 
> ```
>         -n, --dry-run               show what would have been transferred
> ```
> 
> from patch:
> 
> ```
>           Print the results of applying the patches without actually changing any files.
> ```
> 
> from make:
> 
> ```
>             Print the commands that would be executed, but do not execute them.
> ```

Like all three ways better than what we have now, but would vote for "patch" or "make" (nr. 2 or 3) rather than "rsync" (nr 1), because nr 1 is using the  "would have" which might not be thoroughly practised/understood by non-native english speakers.

**Comment by jburel** [comment]
see https://github.com/ome/omero-cli-duplicate/pull/25
