### ISSUE TITLE
Duplicated images can't be opened

### ISSUE THREAD

**Issue by dominikl** [ome/omero-cli-duplicate#9]
If one duplicates a dataset the images are duplicated as well like expected. But it looks like the rendering is never properly initialized for them: No thumbnails and images can't be opened.

![Screen Shot 2019-11-21 at 10 03 32](https://user-images.githubusercontent.com/6575139/69328091-8a8d9500-0c46-11ea-9ad4-bd06b64fa5e0.png)

**Comment by mtbc** [comment]
Fixed by https://github.com/ome/omero-blitz/pull/100.
